previewsEnabled: true
previewsExpireAfterDays: 3

services:
  - type: web
    plan: free
    name: armor-front
    env: node
    branch: main
    startCommand: yarn start
    buildCommand: yarn install && yarn build
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
    autoDeploy: true
