name: Build check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Run build checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install project
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run typecheck
        uses: borales/actions-yarn@v4
        with:
          cmd: typecheck
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
